#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '\n🏗️👷 Typechecking, styling and linting your project before committing\n'

yarn lint-staged ||
(
    echo '\n🤡😂❌🤡 Failed to style abd lint code. 🤡😂❌🤡 \nMake the required changes listed above, add changes and try to commit again.\n'
    false;
)

# If everything passes... Now we can commit
echo '\n🤔🤔🤔🤔... Alright... Code looks good to me...\n'
